on:
  push:
    tags:
    - '*'

jobs:
  push:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Checkout root repository
      uses: actions/checkout@v2
      with:
        repository: sandpolis/sandpolis
    - name: Checkout submodules
      run: |
        git submodule update --init --remote --merge com.sandpolis.server.vanilla
    - name: Initialize QEMU
      uses: docker/setup-qemu-action@v1
    - name: Initialize buildx
      uses: docker/setup-buildx-action@v1
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: DockerHub push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: com.sandpolis.server.vanilla/Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
        push: true
        tags: sandpolis/server:latest
